
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'ImageSlider' do
   pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire'
   pod 'AlamofireImage', :git => 'https://github.com/Alamofire/AlamofireImage'
  
end
